### ISSUE TITLE
リクエストごとのPHPファイルのスキャンの改善

### ISSUE THREAD

**Issue by harai** [inc2734/wp-awesome-widgets#3]
inc2734/snow-monkey#1043 と関連して、次の箇所でも同様にリクエストごとにPHPファイルのスキャンが行われているようです。

https://github.com/inc2734/wp-awesome-widgets/blob/4c8d06481ed663b316a1f10df881d9a1e43c802c/src/Bootstrap.php#L19-L45

ビルド時に実施するよう改良してもらえないでしょうか。

**Comment by harai** [comment]
このissueですが、 [デバッグモードの無効化](https://github.com/inc2734/snow-monkey/issues/1043#issuecomment-817595777) に比べて影響は少ないものの、実行時にスキャンするのは変わりないのでやはり改善の余地はあるんです。

inc2734/snow-monkey#1043 で行ったように前もってファイルの一覧を作成しておくことで、特にネットワークファイルシステムを使った環境下でレスポンス速度の向上と通信量の低下が望めます。

**Comment by inc2734** [comment]
Snow Monkey 本体の場合は子テーマやプラグインからファイルを差し替えられるようにするための仕組み（+ 読み込み方式をフィルターフックで変更できる）があったので、それをこわしてしまわないようにビルド時に読み込むファイルの一覧を生成する方式にしましたが、このライブラリの場合は子テーマやプラグインからファイルを差し替える仕組みはないので単純に `include_once()` を列挙する方式に書き換えました。ディレクトリのスキャンはなくなったのでこれで大丈夫だと思ったのですが違ってましたかね…？

**Comment by harai** [comment]
あっ、失礼しました。直ってたんですね！ ありがとうございます。

**Comment by inc2734** [comment]
間違えてなくてよかったです！プラグインやライブラリは以前からスキャンのところを気づいたときに `include_once()` にするようにしていたのですが、今回ご指摘いただいたライブラリは見逃していたので助かりました。
